### ISSUE TITLE
Nvim crashes in case execute NvChadUpdate command

### ISSUE THREAD

**Issue by pkropachev** [siduck76/NvChad#2666]
**Describe the bug**
Nvim crashes in case execute `NvChadUpdate`.

**To Reproduce**
1. Open `nvim`.
2. Execute command `NvChadUpdate`.
3. `nvim` is exited.

**Expected behavior**
`nvim` should not crashed.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/34160907/bbacab92-f30a-4713-bba2-844443db9e54)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Terminator 2.1.3
 - Neovim 0.9.5

**Additional context**
In my case I use `NVIM_APPNAME` variable to run `nvim` with different configurations.

```
alias nv='NVIM_APPNAME=LazyVim nvim'                                                                
alias nd='NVIM_APPNAME=NvChad nvim'
```

Stack trace:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007faf28921859 in __GI_abort () at abort.c:79
#2  0x00007faf28921729 in __assert_fail_base (fmt=0x7faf28ab7588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55d58e107279 "!uv__is_closing(handle)", 
    file=0x55d58e107240 "/__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c", line=147, function=<optimized out>) at assert.c:92
#3  0x00007faf28932fd6 in __GI___assert_fail (assertion=0x55d58e107279 "!uv__is_closing(handle)", file=0x55d58e107240 "/__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c", line=147, 
    function=0x55d58e1074b8 <__PRETTY_FUNCTION__.12> "uv_close") at assert.c:101
#4  0x000055d58e06466d in uv_close (handle=0x55d58f0ade78, close_cb=0x55d58dd739d0 <close_cb.lto_priv>) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:147
#5  0x000055d58dd7c89d in write_cb ()
#6  0x000055d58e0761b6 in uv__write_callbacks (stream=0x55d58f0ade78) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/stream.c:926
#7  0x000055d58e0752b2 in uv__stream_destroy (stream=0x55d58f0ade78) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/stream.c:466
#8  0x000055d58e064a5e in uv__finish_close (handle=0x55d58f0ade78) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:334
#9  0x000055d58e064b56 in uv__run_closing_handles (loop=0x55d58e3c4560 <main_loop>) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:364
#10 0x000055d58e064e36 in uv_run (loop=0x55d58e3c4560 <main_loop>, mode=UV_RUN_DEFAULT) at /__w/neovim/neovim/.deps/build/src/libuv/src/unix/core.c:462
#11 0x000055d58dd7cb73 in loop_close ()
#12 0x000055d58dc92354 in os_exit ()
#13 0x000055d58dc92451 in getout ()
#14 0x000055d58dd9752e in ex_exit.lto_priv ()
#15 0x000055d58dd8f165 in execute_cmd0 ()
#16 0x000055d58dd929f4 in do_cmdline ()
#17 0x000055d58df83c8f in source_using_linegetter.constprop ()
#18 0x000055d58dcd5e91 in exec_impl ()
#19 0x000055d58dcd60ec in nvim_exec2 ()
#20 0x000055d58dca4914 in nlua_api_nvim_exec2.lto_priv ()
#21 0x000055d58e014ef6 in lj_BC_FUNCC ()
#22 0x000055d58e0014b2 in lua_pcall (L=0x7faf28364380, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at lj_api.c:1116
#23 0x000055d58dde9488 in nlua_pcall.lto_priv ()
#24 0x000055d58ddfa4b1 in nlua_do_ucmd ()
#25 0x000055d58df510c3 in do_ucmd ()
#26 0x000055d58dd8f1c4 in execute_cmd0 ()
#27 0x000055d58dd929f4 in do_cmdline ()
#28 0x000055d58de4ecf3 in nv_colon.lto_priv ()
#29 0x000055d58de4660b in normal_execute.lto_priv ()
#30 0x000055d58df0dca1 in state_enter ()
#31 0x000055d58de45d6b in normal_enter ()
#32 0x000055d58dc8f7ac in main ()
```

I tried delete config in `~/.local/share` and `~/.local/state` directories, but it didn't help.

**Comment by siduck** [comment]
run lazy sync
